name: Flex
markdown: redcarpet
pygments: true

# theme: jekyll-theme-flex
# url: https://gaa101.github.io/
# baseurl: /flex_resume/
# title: Resume
# description: This is Gio Aprigliano's Resume site
# instagram: "http://instagram.com/username"
# author: Gio Aprigliano